# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'JUN15.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from glue import *

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1152, 864)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1121, 841))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser.setGeometry(QtCore.QRect(20, 20, 1081, 781))
        self.textBrowser.setObjectName("textBrowser")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.frame = QtWidgets.QFrame(self.tab_2)
        self.frame.setGeometry(QtCore.QRect(10, 10, 671, 111))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 651, 91))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.norm_folder = QtWidgets.QPlainTextEdit(self.groupBox)
        self.norm_folder.setGeometry(QtCore.QRect(10, 30, 631, 51))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.norm_folder.setFont(font)
        self.norm_folder.setPlainText("")
        self.norm_folder.setOverwriteMode(True)
        self.norm_folder.setObjectName("norm_folder")
        self.frame_2 = QtWidgets.QFrame(self.tab_2)
        self.frame_2.setGeometry(QtCore.QRect(10, 130, 671, 561))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 651, 321))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.norm_radio_vn = QtWidgets.QRadioButton(self.groupBox_2)
        self.norm_radio_vn.setGeometry(QtCore.QRect(20, 60, 121, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.norm_radio_vn.setFont(font)
        self.norm_radio_vn.setObjectName("norm_radio_vn")
        self.norm_radio_gn = QtWidgets.QRadioButton(self.groupBox_2)
        self.norm_radio_gn.setGeometry(QtCore.QRect(20, 90, 121, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.norm_radio_gn.setFont(font)
        self.norm_radio_gn.setObjectName("norm_radio_gn")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(160, 60, 561, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(160, 30, 91, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(20, 30, 91, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(160, 90, 561, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(160, 110, 561, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(160, 130, 561, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.norm_radio_vz = QtWidgets.QRadioButton(self.groupBox_2)
        self.norm_radio_vz.setGeometry(QtCore.QRect(20, 160, 121, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.norm_radio_vz.setFont(font)
        self.norm_radio_vz.setObjectName("norm_radio_vz")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(160, 160, 561, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.norm_radio_gz = QtWidgets.QRadioButton(self.groupBox_2)
        self.norm_radio_gz.setGeometry(QtCore.QRect(20, 190, 121, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.norm_radio_gz.setFont(font)
        self.norm_radio_gz.setObjectName("norm_radio_gz")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(160, 190, 561, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(160, 210, 561, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(160, 230, 561, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.norm_radio_cn = QtWidgets.QRadioButton(self.groupBox_2)
        self.norm_radio_cn.setGeometry(QtCore.QRect(20, 260, 121, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.norm_radio_cn.setFont(font)
        self.norm_radio_cn.setObjectName("norm_radio_cn")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(160, 260, 561, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.norm_radio_nn = QtWidgets.QRadioButton(self.groupBox_2)
        self.norm_radio_nn.setGeometry(QtCore.QRect(20, 290, 121, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.norm_radio_nn.setFont(font)
        self.norm_radio_nn.setObjectName("norm_radio_nn")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(160, 290, 561, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(10, 350, 651, 201))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_13 = QtWidgets.QLabel(self.frame_3)
        self.label_13.setGeometry(QtCore.QRect(10, 10, 211, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame_3)
        self.label_14.setGeometry(QtCore.QRect(20, 40, 71, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.norm_text_shift = QtWidgets.QLineEdit(self.frame_3)
        self.norm_text_shift.setGeometry(QtCore.QRect(100, 40, 61, 23))
        self.norm_text_shift.setText("")
        self.norm_text_shift.setClearButtonEnabled(False)
        self.norm_text_shift.setObjectName("norm_text_shift")
        self.label_15 = QtWidgets.QLabel(self.frame_3)
        self.label_15.setGeometry(QtCore.QRect(20, 70, 71, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.frame_3)
        self.label_16.setGeometry(QtCore.QRect(20, 100, 71, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.frame_3)
        self.label_17.setGeometry(QtCore.QRect(20, 150, 71, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.norm_text_scale = QtWidgets.QLineEdit(self.frame_3)
        self.norm_text_scale.setGeometry(QtCore.QRect(100, 70, 61, 23))
        self.norm_text_scale.setText("")
        self.norm_text_scale.setObjectName("norm_text_scale")
        self.norm_text_cropa = QtWidgets.QLineEdit(self.frame_3)
        self.norm_text_cropa.setGeometry(QtCore.QRect(100, 100, 61, 23))
        self.norm_text_cropa.setObjectName("norm_text_cropa")
        self.norm_text_cropb = QtWidgets.QLineEdit(self.frame_3)
        self.norm_text_cropb.setGeometry(QtCore.QRect(100, 150, 61, 23))
        self.norm_text_cropb.setObjectName("norm_text_cropb")
        self.label_18 = QtWidgets.QLabel(self.frame_3)
        self.label_18.setGeometry(QtCore.QRect(180, 40, 441, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.frame_3)
        self.label_19.setGeometry(QtCore.QRect(180, 70, 441, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.frame_3)
        self.label_20.setGeometry(QtCore.QRect(180, 100, 451, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.frame_3)
        self.label_21.setGeometry(QtCore.QRect(180, 120, 441, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.frame_3)
        self.label_22.setGeometry(QtCore.QRect(180, 150, 441, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.frame_3)
        self.label_23.setGeometry(QtCore.QRect(180, 170, 441, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.norm_button_start = QtWidgets.QPushButton(self.tab_2)
        self.norm_button_start.setGeometry(QtCore.QRect(690, 10, 80, 23))
        self.norm_button_start.setObjectName("norm_button_start")
        self.norm_logger = QtWidgets.QTextBrowser(self.tab_2)
        self.norm_logger.setGeometry(QtCore.QRect(690, 40, 411, 651))
        self.norm_logger.setObjectName("norm_logger")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.frame_5 = QtWidgets.QFrame(self.tab_3)
        self.frame_5.setGeometry(QtCore.QRect(10, 10, 671, 381))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame_5)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 10, 651, 361))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setCheckable(False)
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_27 = QtWidgets.QLabel(self.groupBox_4)
        self.label_27.setGeometry(QtCore.QRect(20, 60, 61, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.groupBox_4)
        self.label_28.setGeometry(QtCore.QRect(20, 110, 61, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_30 = QtWidgets.QLabel(self.groupBox_4)
        self.label_30.setGeometry(QtCore.QRect(20, 30, 91, 21))
        self.label_30.setObjectName("label_30")
        self.n2i_text_axes = QtWidgets.QLineEdit(self.groupBox_4)
        self.n2i_text_axes.setGeometry(QtCore.QRect(120, 60, 41, 23))
        self.n2i_text_axes.setText("")
        self.n2i_text_axes.setClearButtonEnabled(False)
        self.n2i_text_axes.setObjectName("n2i_text_axes")
        self.label_31 = QtWidgets.QLabel(self.groupBox_4)
        self.label_31.setGeometry(QtCore.QRect(170, 30, 91, 21))
        self.label_31.setObjectName("label_31")
        self.label_29 = QtWidgets.QLabel(self.groupBox_4)
        self.label_29.setGeometry(QtCore.QRect(170, 60, 461, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_32 = QtWidgets.QLabel(self.groupBox_4)
        self.label_32.setGeometry(QtCore.QRect(170, 80, 461, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.groupBox_4)
        self.label_33.setGeometry(QtCore.QRect(170, 110, 461, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.groupBox_4)
        self.label_34.setGeometry(QtCore.QRect(170, 130, 461, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.groupBox_4)
        self.label_35.setGeometry(QtCore.QRect(170, 150, 461, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.n2i_text_imsize = QtWidgets.QLineEdit(self.groupBox_4)
        self.n2i_text_imsize.setGeometry(QtCore.QRect(120, 110, 41, 23))
        self.n2i_text_imsize.setText("")
        self.n2i_text_imsize.setClearButtonEnabled(False)
        self.n2i_text_imsize.setObjectName("n2i_text_imsize")
        self.label_36 = QtWidgets.QLabel(self.groupBox_4)
        self.label_36.setGeometry(QtCore.QRect(170, 180, 461, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.groupBox_4)
        self.label_37.setGeometry(QtCore.QRect(20, 180, 61, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.n2i_text_xslices = QtWidgets.QLineEdit(self.groupBox_4)
        self.n2i_text_xslices.setGeometry(QtCore.QRect(120, 180, 41, 23))
        self.n2i_text_xslices.setText("")
        self.n2i_text_xslices.setClearButtonEnabled(False)
        self.n2i_text_xslices.setObjectName("n2i_text_xslices")
        self.label_38 = QtWidgets.QLabel(self.groupBox_4)
        self.label_38.setGeometry(QtCore.QRect(170, 210, 461, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.n2i_text_yslices = QtWidgets.QLineEdit(self.groupBox_4)
        self.n2i_text_yslices.setGeometry(QtCore.QRect(120, 210, 41, 23))
        self.n2i_text_yslices.setText("")
        self.n2i_text_yslices.setClearButtonEnabled(False)
        self.n2i_text_yslices.setObjectName("n2i_text_yslices")
        self.label_39 = QtWidgets.QLabel(self.groupBox_4)
        self.label_39.setGeometry(QtCore.QRect(20, 210, 61, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.groupBox_4)
        self.label_40.setGeometry(QtCore.QRect(170, 240, 461, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.n2i_text_testfraction = QtWidgets.QLineEdit(self.groupBox_4)
        self.n2i_text_testfraction.setGeometry(QtCore.QRect(120, 240, 41, 23))
        self.n2i_text_testfraction.setText("")
        self.n2i_text_testfraction.setClearButtonEnabled(False)
        self.n2i_text_testfraction.setObjectName("n2i_text_testfraction")
        self.label_41 = QtWidgets.QLabel(self.groupBox_4)
        self.label_41.setGeometry(QtCore.QRect(20, 240, 61, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.groupBox_4)
        self.label_42.setGeometry(QtCore.QRect(20, 270, 81, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.groupBox_4)
        self.label_43.setGeometry(QtCore.QRect(170, 270, 461, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.n2i_text_valfraction = QtWidgets.QLineEdit(self.groupBox_4)
        self.n2i_text_valfraction.setGeometry(QtCore.QRect(120, 270, 41, 23))
        self.n2i_text_valfraction.setText("")
        self.n2i_text_valfraction.setClearButtonEnabled(False)
        self.n2i_text_valfraction.setObjectName("n2i_text_valfraction")
        self.n2i_check_force = QtWidgets.QCheckBox(self.groupBox_4)
        self.n2i_check_force.setGeometry(QtCore.QRect(20, 300, 91, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.n2i_check_force.setFont(font)
        self.n2i_check_force.setObjectName("n2i_check_force")
        self.label_44 = QtWidgets.QLabel(self.groupBox_4)
        self.label_44.setGeometry(QtCore.QRect(100, 300, 521, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.n2i_check_shuffle = QtWidgets.QCheckBox(self.groupBox_4)
        self.n2i_check_shuffle.setGeometry(QtCore.QRect(20, 330, 91, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.n2i_check_shuffle.setFont(font)
        self.n2i_check_shuffle.setObjectName("n2i_check_shuffle")
        self.label_45 = QtWidgets.QLabel(self.groupBox_4)
        self.label_45.setGeometry(QtCore.QRect(100, 330, 521, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.frame_6 = QtWidgets.QFrame(self.tab_3)
        self.frame_6.setGeometry(QtCore.QRect(10, 400, 671, 401))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.groupBox_5 = QtWidgets.QGroupBox(self.frame_6)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 10, 651, 381))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_46 = QtWidgets.QLabel(self.groupBox_5)
        self.label_46.setGeometry(QtCore.QRect(20, 30, 91, 21))
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.groupBox_5)
        self.label_47.setGeometry(QtCore.QRect(170, 30, 91, 21))
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.groupBox_5)
        self.label_48.setGeometry(QtCore.QRect(190, 60, 451, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.n2i_text_augfactor = QtWidgets.QLineEdit(self.groupBox_5)
        self.n2i_text_augfactor.setGeometry(QtCore.QRect(120, 60, 41, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.n2i_text_augfactor.setFont(font)
        self.n2i_text_augfactor.setClearButtonEnabled(False)
        self.n2i_text_augfactor.setObjectName("n2i_text_augfactor")
        self.label_49 = QtWidgets.QLabel(self.groupBox_5)
        self.label_49.setGeometry(QtCore.QRect(20, 60, 81, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.groupBox_5)
        self.label_50.setGeometry(QtCore.QRect(190, 90, 451, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.n2i_text_augseed = QtWidgets.QLineEdit(self.groupBox_5)
        self.n2i_text_augseed.setGeometry(QtCore.QRect(120, 90, 41, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.n2i_text_augseed.setFont(font)
        self.n2i_text_augseed.setClearButtonEnabled(False)
        self.n2i_text_augseed.setObjectName("n2i_text_augseed")
        self.label_51 = QtWidgets.QLabel(self.groupBox_5)
        self.label_51.setGeometry(QtCore.QRect(20, 90, 81, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.groupBox_5)
        self.label_52.setGeometry(QtCore.QRect(190, 120, 451, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.n2i_text_addnoise = QtWidgets.QLineEdit(self.groupBox_5)
        self.n2i_text_addnoise.setGeometry(QtCore.QRect(120, 120, 41, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.n2i_text_addnoise.setFont(font)
        self.n2i_text_addnoise.setClearButtonEnabled(False)
        self.n2i_text_addnoise.setObjectName("n2i_text_addnoise")
        self.label_53 = QtWidgets.QLabel(self.groupBox_5)
        self.label_53.setGeometry(QtCore.QRect(20, 120, 81, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.groupBox_5)
        self.label_54.setGeometry(QtCore.QRect(190, 150, 451, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.n2i_text_rotations = QtWidgets.QLineEdit(self.groupBox_5)
        self.n2i_text_rotations.setGeometry(QtCore.QRect(120, 150, 41, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.n2i_text_rotations.setFont(font)
        self.n2i_text_rotations.setClearButtonEnabled(False)
        self.n2i_text_rotations.setObjectName("n2i_text_rotations")
        self.label_55 = QtWidgets.QLabel(self.groupBox_5)
        self.label_55.setGeometry(QtCore.QRect(20, 150, 81, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.groupBox_5)
        self.label_56.setGeometry(QtCore.QRect(190, 180, 451, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.n2i_text_scalings = QtWidgets.QLineEdit(self.groupBox_5)
        self.n2i_text_scalings.setGeometry(QtCore.QRect(120, 180, 41, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.n2i_text_scalings.setFont(font)
        self.n2i_text_scalings.setClearButtonEnabled(False)
        self.n2i_text_scalings.setObjectName("n2i_text_scalings")
        self.label_57 = QtWidgets.QLabel(self.groupBox_5)
        self.label_57.setGeometry(QtCore.QRect(20, 180, 81, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_57.setFont(font)
        self.label_57.setObjectName("label_57")
        self.label_58 = QtWidgets.QLabel(self.groupBox_5)
        self.label_58.setGeometry(QtCore.QRect(190, 210, 451, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_58.setFont(font)
        self.label_58.setObjectName("label_58")
        self.n2i_text_shear = QtWidgets.QLineEdit(self.groupBox_5)
        self.n2i_text_shear.setGeometry(QtCore.QRect(120, 210, 41, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.n2i_text_shear.setFont(font)
        self.n2i_text_shear.setClearButtonEnabled(False)
        self.n2i_text_shear.setObjectName("n2i_text_shear")
        self.label_59 = QtWidgets.QLabel(self.groupBox_5)
        self.label_59.setGeometry(QtCore.QRect(20, 210, 81, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_59.setFont(font)
        self.label_59.setObjectName("label_59")
        self.label_60 = QtWidgets.QLabel(self.groupBox_5)
        self.label_60.setGeometry(QtCore.QRect(190, 240, 451, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_60.setFont(font)
        self.label_60.setObjectName("label_60")
        self.n2i_text_translations = QtWidgets.QLineEdit(self.groupBox_5)
        self.n2i_text_translations.setGeometry(QtCore.QRect(120, 240, 41, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.n2i_text_translations.setFont(font)
        self.n2i_text_translations.setClearButtonEnabled(False)
        self.n2i_text_translations.setObjectName("n2i_text_translations")
        self.label_61 = QtWidgets.QLabel(self.groupBox_5)
        self.label_61.setGeometry(QtCore.QRect(20, 240, 81, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_61.setFont(font)
        self.label_61.setObjectName("label_61")
        self.label_62 = QtWidgets.QLabel(self.groupBox_5)
        self.label_62.setGeometry(QtCore.QRect(20, 270, 71, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_62.setFont(font)
        self.label_62.setObjectName("label_62")
        self.label_63 = QtWidgets.QLabel(self.groupBox_5)
        self.label_63.setGeometry(QtCore.QRect(190, 270, 451, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_63.setFont(font)
        self.label_63.setObjectName("label_63")
        self.label_64 = QtWidgets.QLabel(self.groupBox_5)
        self.label_64.setGeometry(QtCore.QRect(190, 290, 451, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_64.setFont(font)
        self.label_64.setObjectName("label_64")
        self.n2i_radio_augmode_mirror = QtWidgets.QRadioButton(self.groupBox_5)
        self.n2i_radio_augmode_mirror.setGeometry(QtCore.QRect(30, 310, 71, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.n2i_radio_augmode_mirror.setFont(font)
        self.n2i_radio_augmode_mirror.setObjectName("n2i_radio_augmode_mirror")
        self.n2i_radio_augmode_nearest = QtWidgets.QRadioButton(self.groupBox_5)
        self.n2i_radio_augmode_nearest.setGeometry(QtCore.QRect(100, 290, 71, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.n2i_radio_augmode_nearest.setFont(font)
        self.n2i_radio_augmode_nearest.setObjectName("n2i_radio_augmode_nearest")
        self.n2i_radio_augmode_reflect = QtWidgets.QRadioButton(self.groupBox_5)
        self.n2i_radio_augmode_reflect.setGeometry(QtCore.QRect(30, 290, 71, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.n2i_radio_augmode_reflect.setFont(font)
        self.n2i_radio_augmode_reflect.setObjectName("n2i_radio_augmode_reflect")
        self.n2i_radio_augmode_warp = QtWidgets.QRadioButton(self.groupBox_5)
        self.n2i_radio_augmode_warp.setGeometry(QtCore.QRect(100, 310, 71, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.n2i_radio_augmode_warp.setFont(font)
        self.n2i_radio_augmode_warp.setObjectName("n2i_radio_augmode_warp")
        self.label_66 = QtWidgets.QLabel(self.groupBox_5)
        self.label_66.setGeometry(QtCore.QRect(190, 330, 451, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_66.setFont(font)
        self.label_66.setObjectName("label_66")
        self.label_67 = QtWidgets.QLabel(self.groupBox_5)
        self.label_67.setGeometry(QtCore.QRect(190, 350, 451, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_67.setFont(font)
        self.label_67.setObjectName("label_67")
        self.n2i_check_hflips = QtWidgets.QCheckBox(self.groupBox_5)
        self.n2i_check_hflips.setGeometry(QtCore.QRect(20, 330, 111, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.n2i_check_hflips.setFont(font)
        self.n2i_check_hflips.setObjectName("n2i_check_hflips")
        self.n2i_check_vflips = QtWidgets.QCheckBox(self.groupBox_5)
        self.n2i_check_vflips.setGeometry(QtCore.QRect(20, 350, 111, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.n2i_check_vflips.setFont(font)
        self.n2i_check_vflips.setObjectName("n2i_check_vflips")
        self.n2i_radio_aug = QtWidgets.QRadioButton(self.frame_6)
        self.n2i_radio_aug.setGeometry(QtCore.QRect(10, 10, 111, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.n2i_radio_aug.setFont(font)
        self.n2i_radio_aug.setObjectName("n2i_radio_aug")
        self.n2i_button_start = QtWidgets.QPushButton(self.tab_3)
        self.n2i_button_start.setGeometry(QtCore.QRect(690, 10, 80, 23))
        self.n2i_button_start.setObjectName("n2i_button_start")
        self.n2i_logger = QtWidgets.QTextBrowser(self.tab_3)
        self.n2i_logger.setGeometry(QtCore.QRect(690, 40, 411, 551))
        self.n2i_logger.setObjectName("n2i_logger")
        self.frame_4 = QtWidgets.QFrame(self.tab_3)
        self.frame_4.setGeometry(QtCore.QRect(690, 600, 411, 201))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame_4)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 391, 181))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.n2i_folder_X = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.n2i_folder_X.setGeometry(QtCore.QRect(10, 50, 371, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.n2i_folder_X.setFont(font)
        self.n2i_folder_X.setPlainText("")
        self.n2i_folder_X.setOverwriteMode(True)
        self.n2i_folder_X.setObjectName("n2i_folder_X")
        self.label_24 = QtWidgets.QLabel(self.groupBox_3)
        self.label_24.setGeometry(QtCore.QRect(10, 30, 61, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.groupBox_3)
        self.label_25.setGeometry(QtCore.QRect(10, 80, 61, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.n2i_folder_Y = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.n2i_folder_Y.setGeometry(QtCore.QRect(10, 100, 371, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.n2i_folder_Y.setFont(font)
        self.n2i_folder_Y.setPlainText("")
        self.n2i_folder_Y.setOverwriteMode(True)
        self.n2i_folder_Y.setObjectName("n2i_folder_Y")
        self.label_26 = QtWidgets.QLabel(self.groupBox_3)
        self.label_26.setGeometry(QtCore.QRect(10, 130, 61, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.n2i_folder_output = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.n2i_folder_output.setGeometry(QtCore.QRect(10, 150, 371, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.n2i_folder_output.setFont(font)
        self.n2i_folder_output.setPlainText("")
        self.n2i_folder_output.setOverwriteMode(True)
        self.n2i_folder_output.setObjectName("n2i_folder_output")
        self.tabWidget.addTab(self.tab_3, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.norm_button_start.clicked.connect(self.connect_to_backend_norm)
        self.n2i_button_start.clicked.connect(self.connect_to_backend_n2i)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">DeepRad-Tools</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Commandline tools to facilitate the use of Medical Images (from NifTI files) to standard image files (TIFF files) so that these datasets can be readily consumed by deep learning frameworks as used for computer vision.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">It currently consists of three tools: <span style=\" font-weight:600; font-style:italic;\">deeprad_keras_tools</span><span style=\" font-style:italic;\">, </span><span style=\" font-weight:600; font-style:italic;\">deeprad_nii2img</span>, and <span style=\" font-weight:600; font-style:italic;\">deeprad_normalize.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600; font-style:italic;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">DeepRad-Tools</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">This tool converts organized folders of NifTI images (.nii or .nii.gz files) to standard TIFF files and optionally performs augmentation (random alterations) to input images. The rationale for this tool is that image file formats that are often used in medical imaging are not directly compatible with software frameworks that are most commonly used for deep learning. This tool takes NifTI data, which is a convenient format for volumetric medical imaging data because it maintains subject-specific spatial transformations of pixel data. For more information about NifTI, go here: https://nifti.nimh.nih.gov</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">This tool takes folders containing NifTI data as input and writes a new folder structure containing TIFF files that can be readily consumed by a variety of deep learning tools. The advantage of using this strategy is that datasets that are larger than the physical RAM of a system can be readily consumed. While there is likely an I/O performance loss compared to other big data storage strategies such as HDF, there is a great deal of flexibility presented by the proposed approach. First, given that standard image files are used, they are readily viewed and consumed by a wide range of existing software tools. This is incredibly useful for performing visual checks of input and output data. Second, because images are written as floating-point 32-bit floating point data, there is little or no loss to dyanmic range as would occur with integer file formats. Finally, the tool utilizes a reshaping strategy to enable multiple inputs and/or 3D inputs to be provided by writing into 2D images. Because reshaping is a common operation, it is straightforward to reshape inputs and outputs to use TIFF images as an intermediate format.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Note that it is a pre-requisite to use DeepRad Normalize (deeprad_normalize) before using this tool to calculate the proper scale factors for input and output data.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Input is expected as a list of one or more folders for input (--X) and target output ground truth (--Y) data. Output is written into the specified folder (--outfolder) in the following format if validation or testing fractions are specified:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">```</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    -OUTFOLDER</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        -X</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            -test</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            -train</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            -val</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        -Y</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            -test</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            -train</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            -val</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">```</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Or if validiation or tesing fractions are not specified:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">```</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    -OUTFOLDER</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        -X</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        -Y</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">```</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">This folder structure will facilitate integration into a variety of deep learning frameworks</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Current limitations of 06/2019:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> - only handles 2D slices, 3D patches coming soon</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> - is optimized to image-to-image translations, segmentation needs to be validated. Classification and regression capability (mapped to a CSV file) are forthcoming</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> - augmentation strategies are currently limited to affine transformations</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> - 4D NifTI data is not properly handled and will likely break things</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Try running deeprad_nii2img --help for specific help and command line options</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Introduction"))
        self.groupBox.setTitle(_translate("Dialog", "Image Folder"))
        self.groupBox_2.setTitle(_translate("Dialog", "Normalization Options"))
        self.norm_radio_vn.setText(_translate("Dialog", "Volume Norm"))
        self.norm_radio_gn.setText(_translate("Dialog", "Global Norm"))
        self.label.setText(_translate("Dialog", "Normalize input data [0,1] in a volumewise manner"))
        self.label_2.setText(_translate("Dialog", "Description"))
        self.label_3.setText(_translate("Dialog", "Methods"))
        self.label_4.setText(_translate("Dialog", "Normalize input data [0,1] in a global manner"))
        self.label_5.setText(_translate("Dialog", "Caution: ranges are computed volumewise and applied globally. "))
        self.label_6.setText(_translate("Dialog", "This requires two passes through the data"))
        self.norm_radio_vz.setText(_translate("Dialog", "Volume Zscore"))
        self.label_7.setText(_translate("Dialog", "Normalize input data into Z score (data-mean)/stdev in a volumewise manner"))
        self.norm_radio_gz.setText(_translate("Dialog", "Global Zscore"))
        self.label_8.setText(_translate("Dialog", "Normalize input data into Z score (data-mean)/stdev in a global manner"))
        self.label_9.setText(_translate("Dialog", "Caution: ranges are computed volumewise and applied globally. "))
        self.label_10.setText(_translate("Dialog", "This requires two passes through the data"))
        self.norm_radio_cn.setText(_translate("Dialog", "Custom Norm"))
        self.label_11.setText(_translate("Dialog", "Normalize with custom factors: (data-shift)/scale"))
        self.norm_radio_nn.setText(_translate("Dialog", "No Norm"))
        self.label_12.setText(_translate("Dialog", "No normalization is applied."))
        self.label_13.setText(_translate("Dialog", "Parameters for Custom Norm"))
        self.label_14.setText(_translate("Dialog", "Shift"))
        self.label_15.setText(_translate("Dialog", "Scale"))
        self.label_16.setText(_translate("Dialog", "Crop-above"))
        self.label_17.setText(_translate("Dialog", "Crop-below"))
        self.label_18.setText(_translate("Dialog", "User-specified shift to apply"))
        self.label_19.setText(_translate("Dialog", "User-specified scale factor to apply"))
        self.label_20.setText(_translate("Dialog", "Crop pixel values above (greater than) the specified percentile [e.g., 95]."))
        self.label_21.setText(_translate("Dialog", "Note: does not apply to Z score normalizations."))
        self.label_22.setText(_translate("Dialog", "Crop pixel values below (less than) the specified percentile [e.g., 5]."))
        self.label_23.setText(_translate("Dialog", "Note: does not apply to Z score normalizations."))
        self.norm_button_start.setText(_translate("Dialog", "Start"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Normalize"))
        self.groupBox_4.setTitle(_translate("Dialog", "Setting"))
        self.label_27.setText(_translate("Dialog", "Axes"))
        self.label_28.setText(_translate("Dialog", "Imsize"))
        self.label_30.setText(_translate("Dialog", "Parameters"))
        self.label_31.setText(_translate("Dialog", "Description"))
        self.label_29.setText(_translate("Dialog", "Axes of the 3d image array on which to sample the slices"))
        self.label_32.setText(_translate("Dialog", "It can be 0 or 1 or 2 or any multiple combination"))
        self.label_33.setText(_translate("Dialog", "Force size of input images to be X by Y in size. "))
        self.label_34.setText(_translate("Dialog", "This is useful if you are using multiple --axes for non-isotropic data."))
        self.label_35.setText(_translate("Dialog", "If not specified, data will be resized to the size of the first dataset."))
        self.label_36.setText(_translate("Dialog", "Number of adjacent slices to store from input data (X)"))
        self.label_37.setText(_translate("Dialog", "Xslices"))
        self.label_38.setText(_translate("Dialog", "Number of adjacent slices to store from input data (Y)"))
        self.label_39.setText(_translate("Dialog", "Yslices"))
        self.label_40.setText(_translate("Dialog", "Fraction of data as an integer percentage that will be used as testing"))
        self.label_41.setText(_translate("Dialog", "Test ratio"))
        self.label_42.setText(_translate("Dialog", "Validate ratio"))
        self.label_43.setText(_translate("Dialog", "Fraction of data as an integer percentage that will be used as validating"))
        self.n2i_check_force.setText(_translate("Dialog", "Force"))
        self.label_44.setText(_translate("Dialog", "Force writing into existing folder"))
        self.n2i_check_shuffle.setText(_translate("Dialog", "Shuffle"))
        self.label_45.setText(_translate("Dialog", "Shuffle the order of input data. Use with \"augseed\" to produce different samplings"))
        self.label_46.setText(_translate("Dialog", "Parameters"))
        self.label_47.setText(_translate("Dialog", "Description"))
        self.label_48.setText(_translate("Dialog", "This is how many passes through the data augmentation will perform."))
        self.n2i_text_augfactor.setText(_translate("Dialog", "5"))
        self.label_49.setText(_translate("Dialog", "Aug_factor"))
        self.label_50.setText(_translate("Dialog", "Random seed to set for reproducible augmentation"))
        self.n2i_text_augseed.setText(_translate("Dialog", "813"))
        self.label_51.setText(_translate("Dialog", "Aug_seed"))
        self.label_52.setText(_translate("Dialog", "Add Gaussian noise by this factor"))
        self.n2i_text_addnoise.setText(_translate("Dialog", "0"))
        self.label_53.setText(_translate("Dialog", "Add_noise"))
        self.label_54.setText(_translate("Dialog", "Perform random rotations up to this angle (in degrees)"))
        self.n2i_text_rotations.setText(_translate("Dialog", "0"))
        self.label_55.setText(_translate("Dialog", "Rotations"))
        self.label_56.setText(_translate("Dialog", "Perform random scalings between the range [(1-scale),(1+scale)]"))
        self.n2i_text_scalings.setText(_translate("Dialog", "0"))
        self.label_57.setText(_translate("Dialog", "Scaling"))
        self.label_58.setText(_translate("Dialog", "Add random shears by up to this angle (in degrees)"))
        self.n2i_text_shear.setText(_translate("Dialog", "0"))
        self.label_59.setText(_translate("Dialog", "Shears"))
        self.label_60.setText(_translate("Dialog", "Perform random translations by up to this number of pixels"))
        self.n2i_text_translations.setText(_translate("Dialog", "0"))
        self.label_61.setText(_translate("Dialog", "Translations"))
        self.label_62.setText(_translate("Dialog", "Aug_mode"))
        self.label_63.setText(_translate("Dialog", "Determines how the augmented data is extended beyond its boundaries."))
        self.label_64.setText(_translate("Dialog", "See scipy.ndimage documentation for more information"))
        self.n2i_radio_augmode_mirror.setText(_translate("Dialog", "mirror"))
        self.n2i_radio_augmode_nearest.setText(_translate("Dialog", "nearest"))
        self.n2i_radio_augmode_reflect.setText(_translate("Dialog", "reflect"))
        self.n2i_radio_augmode_warp.setText(_translate("Dialog", "warp"))
        self.label_66.setText(_translate("Dialog", "Perform random horizontal flips"))
        self.label_67.setText(_translate("Dialog", "Perform random vertical flips"))
        self.n2i_check_hflips.setText(_translate("Dialog", "Horizontal flips"))
        self.n2i_check_vflips.setText(_translate("Dialog", "Vertical flips"))
        self.n2i_radio_aug.setText(_translate("Dialog", "Augmentation"))
        self.n2i_button_start.setText(_translate("Dialog", "Start"))
        self.groupBox_3.setTitle(_translate("Dialog", "Image Folder"))
        self.label_24.setText(_translate("Dialog", "Folder X"))
        self.label_25.setText(_translate("Dialog", "Folder Y"))
        self.label_26.setText(_translate("Dialog", "Output"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "nii2img"))

    def connect_to_backend_norm(self):
        deeprad_backend_norm(self)

    def connect_to_backend_n2i(self):
        deeprad_backend_n2i(self)